const Map<String, String> ar = {
  "Title": "العنوان",
  "Setting": "الاعدادات",
  "Night mode": "وضع الليلي",
  "Edit Profile": "تعديل الملف الشخصي",
  "Language": "اللغة",
  "About us": "من نحن",
  "Contact Us": "تواصل معنا",
  "LogOut": "تسجيل الخروج",
  "house list": "قائمة المنازل",
  "order": "طلب",
  "house view": "عرض المنزل",
  "Add House": "أضافة بيت",
  "Order": "الطلبات",
  "description": "الوصف",
  "city": "المدينة",
  "age": "العمر",
  "are you sure ?": "are you sure ?",
  "The number of rooms": "عدد الغرف",
  "rant": "rant",
  "Skip": "تخطي",
  "add home": "أضف منزل",
  "Enter the pictures of the house!": "ادخل صور المنزل!",
  "Getting Started": "ابدء",
  "note!!!": "ملاحظة!!!",
  "more information": "المزيد من المعلومات",
  "We will contact you when the number is full":
      "سنقوم بالأتصال بك عند اكتمال العدد",
  "Home rental requests": "طلبات الأيجار",
  "add your university card hear!": "اضغط لأضافة صورة بطاقة الجامعبة",
  "Register": "الاشتراك",
  "university College": "كلية الجامعية",
  "fill out a form": "أملا الاستمارة",
  "academic year": "سنة الجامعية",
  "Insert a photo of your university card": "اضغط لأضافة صورة بطقة الجامعية !",
  "Enter the search word": "أدخل كلمة البحث",
  "Houses": "البيوت",
  "Logout": "تسجيل الخروج",
  "Donation Register": "سجل التبرعات",
  "  money amount:": "قيمة التبرع :",
  "History": "سجلات",
  "money amount": "مبلغ المدفوع",
  "  Payment method:": "طريقة الدفع:   ",
  "Donation": "التبرع",
  "save": "حفظ",
  "if you have any problem just contact with us": "إذا كان لديك أي مشكلة فقط تواصل معنا",
  "your password": "your password",
  "work details": "work details",
  "Find the right home at a price that matches your income.": "اعثر على المنزل المناسب بسعر يتناسب مع دخلك.",
  "press to set id image": "اضغط لادخال صورة هوية هنا!",
  "address": "عنوان",
  "From the heart, Thank you.": "من القلب شكرا.",
  "The ability to add homes for rent and manage them easily.": "إمكانية إضافة منازل للإيجار وإدارتها بسهولة.",
  "Enter id image": "ادخل صورة هوية",
  "donate money": "التبرع المال",
  "Note!": "ملاحظة!",
  "We will contact you when a donation request is received, thank you":
      "سوف نتصل بك عند استلام طلب التبرع ، شكرا لك",
  "Profile": "الملف الشخصي",
  "Enter the donation amount": "ادخل مبلغ التبرع",
  "Please Choose Image": "اختر مكان جلب صورة",
  "Email": "الإيميل ",
  "Phone Number": "رقم الهاتف",
  "Add": "اضافة",
  "Please Choose User": "Please Choose User",
  "SingIn": "SingIn",
  "you have account?": "you have account?",
  "Continue": "الاستمرار",
  "OR": "او",
  "Does not have account?": "ليس لديك حساب ؟",
  "Sign Up": "تسحيل حساب ",
  "Welcome": "مرحبا",
  "don't have account?": "don't have account?",
  "Login": "تسجيل الدخول",
  "Phone :  +963 967 184 204": "رقم الهاتف: 0967184204",
};
