const Map<String, String> en = {
  "Title": "Title",
  "Setting": "Setting",
  "Language": "Language",
  "Contact Us": "Contact Us",
  "Edit Profile": "Edit Profile",
  "Logout": "Logout",
  "Donation Register": "Donation Register",
  "  money amount:": "  money amount:",
  "History": "History",
  "Night mode": "Night mode",
  "money amount": "money amount",
  "  Payment method:": "  Payment method:",
  "Enter the pictures of the house!": "Enter the pictures of the house!",
  "Donation": "Donation",
  "rant": "rant",
  "add home": "add home",
  "The number of rooms": "The number of rooms",
  "donate money": "donate money",
  "Enter the donation amount": "Enter the donation amount",
  "Profile": "Profile",
  "About us": "About us",
  "fill out a form": "fill out a form",
  "add your university card hear!": "add your university card hear!",
  "city": "city",
  "Skip": "Skip",
  "Getting Started": "Getting Started",
  "From the heart, Thank you.": "From the heart, Thank you.",
  "The ability to add homes for rent and manage them easily": "The ability to add homes for rent and manage them easily",
  "Find the right home at a price that matches your income.": "Find the right home at a price that matches your income.",
  "Home rental requests": "Home rental requests",
  "We will contact you when the number is full":
      "We will contact you when the number is full",
  "university College": "university College",
  "age": "age",
  "more information": "more information",
  "note!!!": "note!!!",
  "save": "save",
  "if you have any problem just contact with us": "if you have any problem just contact with us",
  "description": "description",
  "academic year": "academic year",
  "Insert a photo of your university card":
      "Insert a photo of your university card",
  "Please Choose Image": "Please Choose Image",
  "Enter id image": "Enter id image",
  "LogOut": "LogOut",
  "Search": "Search",
  "are you sure ?": "are you sure ?",
  "Note!": "Note!",
  "We will contact you when a donation request is received, thank you":
      "We will contact you when a donation request is received, thank you",
  "Login": "login",
  "Name": "Name",
  "SingIn": "SingIn",
  "you have account?": "you have account?",
  "Houses": "Houses",
  "don\'t have account?": "don\'t have account?",
  "Order": "Order",
  "Email": "Email",
  "address": "address",
  "house view": "house view",
  "Enter the search word": "Enter the search word",
  "order": "order",
  "press to set id image": "press to set id image",
  "Phone Number": "Phone Number",
  "Common Info": "Common Info",
  "Add": "Add",
  "your password": "your password",
  "work details": "work details",
  "Continue": "continue",
  "Register": "register",
  "OR": "OR",
  "house list": "house list",
  "Add House": "Add House",
  "Sign Up": "Sign Up",
  "Welcome": "Welcome",
  "Phone :  +963 988 550 610": "Phone :  +963 988 550 610",
  "Add Products": "Add Products",
};
